name: On Tag Push To develop, PR to dev/pwa and master

on:
  push:
    tags:
      - '**'
    branches:
      - develop

jobs:
  pr-to-targets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all tags & history

      - name: Get tag info
        id: tag
        run: |
          echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Create PR to dev/pwa
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: develop
          target: dev/pwa
          title: 'Merge develop (${{ github.ref_name }}) into dev/pwa'
          body: 'Automated PR to merge develop at tag ${{ github.ref_name }} into dev/pwa.'
          draft: false

      - name: Create PR to master
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          source: develop
          target: master
          title: 'Merge develop (${{ github.ref_name }}) into master'
          body: 'Automated PR to merge develop at tag ${{ github.ref_name }} into master.'
          draft: false
